name: "Core"

web: "[mootools.net](http://mootools.net)"

description: "MooTools, The JavaScript Framework"

license: "[MIT License](http://mootools.net/license.txt)"

copyright: "&copy; [MooTools](http://mootools.net)"

authors: "[The MooTools development team](http://mootools.net/developers)"

inspiration:
  - "Class implementation inspired by [Base.js](http://dean.edwards.name/weblog/2006/03/base/) Copyright (c) 2006 Dean Edwards, [GNU Lesser General Public License](http://opensource.org/licenses/lgpl-license.php)"
  - "Some functionality inspired by [Prototype.js](http://prototypejs.org) Copyright (c) 2005-2007 Sam Stephenson, [MIT License](http://opensource.org/licenses/mit-license.php)"

sources:
  - "Source/Core/Core.js"
  - "Source/Types/Array.js"
  - "Source/Types/Function.js"
  - "Source/Types/Object.js"
  - "Source/Types/String.js"
  - "Source/Types/Number.js"
  - "Source/Class/Class.js"
  - "Source/Class/Events.js"
  - "Source/Class/Store.js"
  - "Source/Class/Options.js"
  - "Source/Class/Chain.js"
  - "Source/Browser/Browser.js"
  - "Source/Browser/Event.js"
  - "Source/Slick/Slick.Parser.js"
  - "Source/Slick/Slick.Finder.js"
  - "Source/Element/Element.js"
  - "Source/Element/Element.Style.js"
  - "Source/Fx/Timer.js"
  - "Source/Fx/Fx.js"
  - "Source/Fx/Fx.Morph.js"
  - "Source/Utilities/Accessor.js"
  - "Source/Utilities/JSON.js"
  - "Source/Utilities/Color.js"
  - "Source/Utilities/Table.js"
